Osnabrück University - Machine Learning (Summer Term 2024) - Prof. Dr.-Ing. G. Heidemann, Ulf Krumnack, Lukas Niehaus

# Exercise Sheet 03: Clustering

## Introduction

This week's sheet should be solved and handed in before the end of **Sunday, May 5th, 2022**. If you need help (and Google and other resources were not enough), feel free to contact your groups designated tutor or whomever of us you run into first. Please upload your results to your group's studip folder.

# Assignment 0: Math recap (Eigenvectors and Eigenvalues) [0 Points]

This exercise does not give any points, and is voluntary. There will be a similar exercise on every sheet. It is intended to revise some basic mathematical notions that are assumed throughout this class and to allow you to check if you are comfortable with them. Eigenvectors and eigenvalues may be less familiar, so this may be a good time to look them up again (you will only need the basic concepts, you do not have to know how to actually compute them for this class). You are always welcome to discuss questions with the tutors or in the practice session. Also, if you have a (math) topic you would like to recap, please let us know.

## a) Eigenvectors and eigenvalues

What is an eigenvector of a matrix/a linear mapping? What are eigenvalues?

Mapping (i.e. multiplying with the matrix) an eigenvector will result a scaled version of that vector, i.e. it may change length and orientation, but not its direction in space. Formally, an eigenvector $v$ fulfills
$$A\cdot v=\lambda v\qquad\text{for some scalar $\lambda\in\mathbb{R}$}$$
The scalar $\lambda$ is called the eigenvalue belonging to the eigenvector $v$.

## b) Characteristic polynomial

What is the characteristic polynomial of a matrix? How is it related to eigenvalues? What are algebraic and geometric multiplicity of an eigenvalue?

The characteristic polynomial of a $n\times n$-matrix $A$ is defined as
$$p_A(X) = \det(X\cdot\mathbf{I}_n-A)$$
where $\mathbf{I}_n$ is the identity matrix and $\det$ the determinant. It is a polynomial of degree $n$, that is invariant under matrix similarity. The roots of the characteristic polynomial are the eigenvalues of the matrix.
The algebraic multiplicity of an eigenvalue $\lambda$ is its multiplicity as a root of the characteristic polynomial.

For every eigenvalue, there may be multiple eigenvectors, that span a subspace called the eigenspace for that eigenvector. The geometric multiplicity of an eigenvalue is the dimension of the corresponding eigenspace. The geometric multiplicity cannot exceed the algebraic multiplicity.

## c) Spectrum

What is the spectrum of a matrix? What does the spectral theorem state?

The spectrum of a matrix is the set of its eigenvalues. The spectral theorem states under which conditions there is diagonalization and provides a cannonical decomposition, referred to es eigendecomposition. For example every real symmetric square matrix is diagonalizable. The diagonalization $A=VDV^T$ consists of a diagonal matrix having the eigenvalues in the diagonal and the matrix $V$ has the corresponding eigenvectors as columns.

## d) Numpy/Scipy [bonus task]

Numpy/Scipy provide functions to compute eigenvalues. Lookup these functions and apply them to an example.

## Assignment 1: p-norm (6 points)

A very well known norm is the euclidean norm. However, it is not the only norm: It is in fact just one of many p-norms where $p = 2$. In this assignment you will take a look at other p-norms and see how they behave.

**(a)** Implement a function `pnorm` which expects a vector $x \in \mathcal{R}^n$ and a scalar $p \geq 1, p \in \mathcal{R}$ and returns the p-norm of $x$ which is defined as:

$$||x||_p = \left(\sum\limits_{i=1}^n |x_i|^p \right)^{\frac{1}{p}}$$

*Note:* Even though the norm is only defined for $p \geq 1$, values $0 < p < 1$ are still interesting. In that case we can not talk about a norm anymore, as the triangle inequality ($||a|| + ||b|| \geq ||a + b||$) does not hold. We will still take a look at some of these values, so your function should handle them as well.

In [ ]:
import numpy as np

def pnorm(x, p):
    """
    Calculates the p-norm of x.
    
    Args:
        x (array): the vector for which the norm is to be computed.
        p (float): the p-value (a positive real number).
        
    Returns:
        The p-norm of x.
    """
    result = None
    ### BEGIN SOLUTION
    # If p is not valid, raise an error:
    if p <= 0:
        raise ValueError('p has to be > 0!')
    result = np.sum(np.abs(x) ** p) ** (1 / p)
    ### END SOLUTION
    return result

In [ ]:
# Epsilon: Account for rounding erros
epsilon = 1e-8
assert abs(pnorm(1, 2)      - 1          ) < epsilon, "pnorm is incorrect for x = 1, p = 2"
assert abs(pnorm(2, 2)      - 2          ) < epsilon, "pnorm is incorrect for x = 2, p = 2"
assert abs(pnorm([2, 1], 2) - np.sqrt(5) ) < epsilon, "pnorm is incorrect for x = [2, 1], p = 2" 
assert abs(pnorm(2, 0.5)    - 2          ) < epsilon, "pnorm is incorrect for x = 2, p = 0.5"

**(b)** Implement another function `pdist` which expects two vectors $x_0 \in \mathcal{R}^n, x_1 \in \mathcal{R}^n$ and a scalar $p \geq 1, p \in \mathcal{R}$ and returns the distance between $x_0$ and $x_1$ on the p-norm defined by $p$. Again handle $0 < p < 1$ as well.

In [ ]:
import numpy as np

def pdist(x0, x1, p):
    """
    Calculates the distance between x0 and x1
    using the p-norm.
    
    Arguments:
        x0 (array): the first vector.
        x1 (array): the second vector.
        p (float): the p-value (a positive real number).
        
    Returns:
        The p-distance between x0 and x1.
    """
    result = None
    ### BEGIN SOLUTION
    result = pnorm(np.array(x0) - np.array(x1), p)
    ### END SOLUTION
    return result

In [ ]:
# Epsilon: Account for rounding erros
epsilon = 1e-8
assert abs(pdist(1, 2, 2)           - 1          ) < epsilon , "pdist is incorrect for x0 = 1, x1 = 2, p = 2"
assert abs(pdist(2, 5, 2)           - 3          ) < epsilon , "pdist is incorrect for x0 = 2, x1 = 5, p = 2"
assert abs(pdist([2, 1], [1, 2], 2) - np.sqrt(2) ) < epsilon , "pdist is incorrect for x0 = [2, 1], x1 = [1, 2], p = 2" 
assert abs(pdist([2, 1], [0, 0], 2) - np.sqrt(5) ) < epsilon , "pdist is incorrect for x0 = [2, 1], x1 = [0, 0], p = 2" 
assert abs(pdist(2, 0, 0.5)         - 2          ) < epsilon , "pdist is incorrect for x0 = 2, x1 = 0, p = 0.5"

**(c)** Now we will compare some different p-norms. Below is part of a code to plot data in nice scatter plots. 

Your task is to calculate the data to plot. The variable `data` is currently simply filled with zeros. Instead, fill it as follows:

- Use the function `np.linspace()` to create a vector of `50` evenly distributed values between `-100` and `100` (inclusively).
- Fill `data`: Data is basically the cartesian product of the vector you created before with itself filled up with each value's norm. It should have 2500 rows. Each of the 2500 rows should contain `[x, y, d]`, where `x` is the x coordinate and `y` the y coordinate of a point, and `d` the p-norm of `(x, y)`. Use either `pnorm` or `pdist` to calculate `d`.
- Normalize the data in `data[:,2]` (i.e. all d-values) so that they are between 0 and 1.

Run your code and take a look at your results. Darker colors mean that a value is further away from the center (0, 0) according to the p-norm used.

*Hint:* To give you an idea of how `data` should look like, here is an example for three evenly distributed values between `-1` and `1` and a p-norm with `p = 2`.

Before normalization of the d-column:

```python
data = np.array([[-1.         -1.          1.41421356]
                 [-1.          0.          1.        ]
                 [-1.          1.          1.41421356]
                 [ 0.         -1.          1.        ]
                 [ 0.          0.          0.        ]
                 [ 0.          1.          1.        ]
                 [ 1.         -1.          1.41421356]
                 [ 1.          0.          1.        ]
                 [ 1.          1.          1.41421356]])
```

After normalization of the d-column:

```python
data = np.array([[-1.         -1.          1.        ]
                 [-1.          0.          0.70710678]
                 [-1.          1.          1.        ]
                 [ 0.         -1.          0.70710678]
                 [ 0.          0.          0.        ]
                 [ 0.          1.          0.70710678]
                 [ 1.         -1.          1.        ]
                 [ 1.          0.          0.70710678]
                 [ 1.          1.          1.        ]])
```

In [ ]:
%matplotlib ipympl
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ColorConverter

color = ColorConverter()
figure_norms = plt.figure('p-norm comparison')

# create the linspace vector
### BEGIN SOLUTION
ls = np.linspace(-100, 100)
### END SOLUTION

assert len(ls) == 50 , 'ls should be of length 50.'
assert (min(ls), max(ls)) == (-100, 100) , 'ls should range from -100 to 100, inclusively.'

for i, p in enumerate([1/8, 1/4, 1/2, 1, 1.5, 2, 4, 8, 128]):
    # Create a numpy array containing useful values instead of zeros.
    data = np.zeros((2500, 3))
    ### BEGIN SOLUTION
    data = np.array([[x, y, pnorm((x, y), p)] for x in ls for y in ls])
    data[:,2] = data[:,2] / np.max(data[:,2])
    ### END SOLUTION

    assert data[100,2]>0.9 and data[100,2]<1, "Wrong result for p norm, make sure you use NORM and not pdist!"
    assert all(data[:,2] <= 1), 'The third column should be normalized.'

    # Plot the data.
    colors = [color.to_rgb((1, 1-a, 1-a)) for a in data[:,2]]
    a = plt.subplot(3, 3, i + 1)
    plt.scatter(data[:,0], data[:,1], marker='.', color=colors)
    a.set_ylim([-100, 100])
    a.set_xlim([-100, 100])
    a.set_title('{:.3g}-norm'.format(p))
    a.set_aspect('equal')
    plt.tight_layout()
    figure_norms.canvas.draw()

**(d)** In the first parts of this exercise we have used the fact that every $p$-norm induces an associated metric by setting $d_p(x,y):=\|x-y\|_p$ for $x,y\in\mathcal{R}^{n}$.  Show that for $p\ge 1$ this function $d_p$ indeed fulfills the conditions listed on ML-04 slide 39. What problems occur for $p<1$?

Hint: start with a specific case, e.g. the Euclidean metric $p=2$ for a low dimension $n$ and then generalize your arguments to other values of $n$ and $p$.

First show symmetry: this is straight forward, just spelling out the definition:
$$d(x,y) = \|x-y\| 
= \left(\sum\limits_{i=1}^n |x_i-y_i|^p \right)^{\frac{1}{p}}
= \left(\sum\limits_{i=1}^n |y_i-x_i|^p \right)^{\frac{1}{p}}
= \|y-x\| = d(y,x)$$
Here we have used the fact that $|a-b|=|-(b-a)| = |b-a|$ for
all real numbers $a,b$.

The coincidence axiom can be seen as follows: Assume that
$$0 = d(x,y) = \|x-y\| = \left(\sum\limits_{i=1}^n |x_i-y_i|^p \right)^{\frac{1}{p}}$$
We use the fact that $a^{\frac{1}{p}}$ can only be $0$ if $a=0$. This implies that the sum $\sum\limits_{i=1}^n |x_i-y_i|^p$ has to be $0$.
We know that $|b|\ge 0$ for all real numbers $b$ and hence $|x_i-y_i|\geq 0$ for all $i=1,\ldots,n$ and further $|x_i-y_i|^p\geq 0$, i.e., none of the summands can be negative.  Hence all have to be $0$, that is $x_i=y_i$ for all $i=1,\ldots,n$. This means $x=y$.

Finally, consider the triangle inequality: Take three points $x,y,z\in\mathcal{R}^{n}$:
Assuming that we know that $\|\cdot\|_p$ is a norm, i.e., that it fulfills the triangle inequality for a norm $\|a+b\|_p\leq \|a\|_p+\|b\|_p$, then we can derive the triangle inequality for the derived metric as
$$d_p(x,y) = \|(x-y)\|_p = \|(x-z) + (z-y)\|_p\leq = \|x-z\|_p + \|z-y\|_p = d_p(x,z) + d_p(z,y)$$
Showing that the norm $\|\cdot\|_p$ in fact obeys the triangle inequality is a bit more challenging (this is known as [Minkowski inequality](https://en.wikipedia.org/wiki/Minkowski_inequality)): for the Euclidean norm ($p=2$) one can for example used the [Cauchy-Schwartz inequality](https://en.wikipedia.org/wiki/Cauchy%E2%80%93Schwarz_inequality) ($\langle x,y\rangle\leq \|x\|_2\|y\|_2$) and then derive:
\begin{align}
  \|x+y\|_2^2 &= \sum_{i=1}^n(x_i+y_i)^2 = \sum_{i=1}^n(x_i^2+2x_iy_i+y_i^2) = 
\sum_{i=1}^n x_i^2+2\sum_{i=1}^n x_iy_i+\sum_{i=1}^n y_i^2 \\
& = 
\|x\|_2^2+2\langle x,y\rangle + \|y\|_2^2 \leq
\|x\|_2^2+2\|x\|_2\|y_i\|_2 + \|y\|_2^2 = (\|x\|_2 + \|y\|_2)^2
\end{align}
For other $p\geq 1$ we will assume that $\|x\|_p+\|y\|_p=1$ and show
$\|x+y\|_p\leq 1$ (the general case follows then by the homogeneity of the norm). Set $\lambda:=\|y\|_p$ and hence $\|x\|=1$, and define $u=x/(1-\lambda)$ and $v=y/\lambda$ (this implies $\|u\|_p=1=\|v\|_p$. We will show
$\|(1-\lambda)u+\lambda v\|_p\leq 1$. For this we use the [convexity](https://en.wikipedia.org/wiki/Convex_function) of the map $z\mapsto |z|^p$ for $p\ge1$, that is the fact that $|tz_1+(1-t)z_2|^p\leq t|z_1|^p+(1-t)|z_2|^p$ for all $z_1,z_2\in\mathbb{R}$ and $t\in[0,1]$. For each component $i=1,\ldots,n$ it hence holds
$$|(1-\lambda) u_i+\lambda v_i|^p \leq (1-\lambda)|u_i|^p + \lambda|v_i|^p$$
Summing up all components we get
\begin{align}
  \left(\|x+y\|_p\right)^p & = \sum_{i=1}^n |x_i+y_i|^p = \sum_{i=1}^n |(1-\lambda)u_i +\lambda+v_i|^p \\
  & \leq \sum_{i=1}^n(1-\lambda)|u_i|^p + \lambda|v_i|^p
  = (1-\lambda)\sum_{i=1}^n|u_i|^p + \lambda\sum_{i=1}^n|y_i|^p \\
  &= (1-\lambda)(\|u\|_p)^p + \lambda(\|v\|_p)^p
  = (1-\lambda)\cdot 1^p + \lambda \cdot 1^p = (1-\lambda) + \lambda \\
  &= 1
\end{align}
To show the general case of the triangle inequaltity (for arbitrary vectors $x$ and $y$, without the norm restriction from above) we use the homogeneity of the $p$-norm, that is the fact that for each real number $\alpha$ it holds that $\|\alpha\cdot x\|_p=|\alpha|\cdot\|x\|_p$ (this follows directly as
$\sum |\alpha x_i|^p = \sum |\alpha|^p\cdot|x_i|^p) = |\alpha|^p(\sum |x_i|^p)$). 
We set  $\kappa=\|x\|_p+\|y\|_p$, so that $x/\kappa$ and $y/\kappa$ are of the desired form (that is $\|x/\kappa\|_p + \|y/\kappa\|_p=1$). Then it follows that
$$\left\|x+y\right\|_p 
= \kappa\left\|\frac{x}{\kappa}+\frac{y}{\kappa}\right\|
\leq \kappa\left(\left\|\frac{x}{\kappa}\right\|_p+\left\|\frac{y}{\kappa}\right\|_p\right)
=\|x\|_p+\|y\|_p$$

# Assignment 2: Distance Measures for Clusters (4 points)

## a) Point and cluster distances

Explain the difference of point and cluster distances and their relation to each other. Give examples.

Clusters are collections of points. The distance of two clusters can be derived from the distance of the points they contain. This requires that distances between points can be measured, i.e., the points are from some metric space. 

## b) Mean and centroid distance

* Describe how the cluster metrics *mean distance* and *centroid distance* work.
* What formal requirements do they have?
* What is their computational complexity (use the [Big O notation](https://en.wikipedia.org/wiki/Big_O_notation))? 
* Give a numerical example of clusters (with cluster size at least 2), where they lead to (a) the same result and (b) different results.

The $D_{\text{centroid}}$ first computes the center of each cluster and then computes the distance of these centers. Hence it can only be applied to clusters that allow to compute such a center (e.g. clusters of points in a euclidean space), while the $D_{\text{mean}}$ metric can be applied to clusters of points in a general metric space (where it is possible to measure the distance of datapoints, but not necessarily to obtain a cluster center). For clusters $X$ and $Y$ the following holds:

* $D_{\text{mean}}$ has complexity $O(|X|\cdot|Y|)$: Compute the sum of the distances of all pairs from $(x,y)$ There exist $|X|\cdot|Y|$ such pairs (actually you only need half of it, as the distance is symmetric, but this does not change the order of complexity). So you have to compute $O(|X|\cdot|Y|)$ distances (the complexity of this operation depends on the distance measure applied) and add up the $O(|X|\cdot|Y|)$ values.
* $D_{\text{centroid}}$ has complexity $O(|X|+|Y|)$: compute the mean of each cluster, which amounts to summing up $|X|$ vectors for cluster $X$ and $|Y|$ vectors for cluster $Y$ - again the complexity of summing vectors depends on the type of vectorspace you consider, it will usually depend directly on its dimensionality.



Numerical example (in the euclidean space $\mathbb{R}^2$): Cluster $X=\{\begin{pmatrix}1\\1\end{pmatrix}, \begin{pmatrix}1\\4\end{pmatrix}\}$, and cluster $Y=\{\begin{pmatrix}5\\1\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\}$.

* (a) Euclidean norm:
    * Centroid distance
    
        The centroid of $X$ is 
        $$\bar{X} = \frac{1}{2}\sum_{x\in X}x = \frac{1}{2}\left[\begin{pmatrix}1\\1\end{pmatrix} + \begin{pmatrix}1\\4\end{pmatrix}\right] = \frac{1}{2}\begin{pmatrix}2\\5\end{pmatrix} = \begin{pmatrix}1\\2.5\end{pmatrix}$$
        and the centroid of $Y$ is 
        $$\bar{Y}=\frac{1}{2}\sum_{y\in Y}y= \frac{1}{2}\left[\begin{pmatrix}5\\1\end{pmatrix} + \begin{pmatrix}5\\4\end{pmatrix}\right] = \frac{1}{2}\begin{pmatrix}10\\5\end{pmatrix} = \begin{pmatrix}5\\2.5\end{pmatrix}$$

        Hence $$D_{\text{centroid}}(X,Y) = \left\|\begin{pmatrix}1\\2.5\end{pmatrix}-\begin{pmatrix}5\\2.5\end{pmatrix}\right\| = \left\|\begin{pmatrix}-4\\ 0\end{pmatrix}\right\| = 4$$

    * Mean distance

        $$D_{\text{mean}}(X,Y) = \frac{1}{2\cdot 2}\left[d\left(\begin{pmatrix}1\\1\end{pmatrix},\begin{pmatrix}5\\1\end{pmatrix}\right) + d\left(\begin{pmatrix}1\\1\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right) + d\left(\begin{pmatrix}1\\4\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right) + d\left(\begin{pmatrix}1\\4\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right)\right]=\frac{1}{4}\left[4 + 5 + 4 + 5\right] = 4.5$$

    * So here $D_{\text{centroid}}(X,Y) \neq D_{\text{mean}}(X,Y)$


* (b) Take the same points but now use the maximum norm instead of the Euclidean norm (alternatively, you could also use a new dataset here).

    * Centroid distance

        The centroids stay the same (they are independent of the underlying norm) and the centroid distance is
        $$D_{\text{centroid}}(X,Y) = d_{\infty}\left(\begin{pmatrix}5\\2.5\end{pmatrix}, \begin{pmatrix}1\\2.5\end{pmatrix}\right) = \max\{|5-1|, |2.5-2.5|\} = \max\{4,0\} = 4$$

    * Mean distance

        $$D_{\text{mean}}(X,Y) = \frac{1}{2\cdot 2}\left[d_{\infty}\left(\begin{pmatrix}1\\1\end{pmatrix},\begin{pmatrix}5\\1\end{pmatrix}\right) + d_{\infty}\left(\begin{pmatrix}1\\1\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right) + d_{\infty}\left(\begin{pmatrix}1\\4\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right) + d_{\infty}\left(\begin{pmatrix}1\\4\end{pmatrix},\begin{pmatrix}5\\4\end{pmatrix}\right)\right]=\frac{1}{4}\left[4 + 4 + 4 + 4\right] = 4$$

    * So now $D_{\text{centroid}}(X,Y) = D_{\text{mean}}(X,Y)$.


## c) Implemention of  mean and centroid distance

Now implement the $d_{mean}$ and $d_{centroid}$ distance from the lecture. Each function expects two clusters each represented by a 2-dimensional numpy array, where the number of columns $n$ reflects the dimensionality of the data space and has to agree for both clusters, while the number of rows $mx$ and $my$ can vary from cluster to cluster. The return value is the respective distance.  Use the Euclidean distance as underlying metric.

Hint: you may consider using the function `scipy.spatial.distance.cdist`. Consult the documentation to find out how to use it.

In [ ]:
from scipy.spatial.distance import cdist
import numpy as np

def d_mean(cluster1, cluster2):
    """
    Mean distance between points of two clusters.
   
    Args:
        cluster1 (ndarray): Points belonging to cluster 1 of shape (num_points, num_dimensions).
        cluster2 (ndarray): Points belonging to cluster 1 of shape (num_points, num_dimensions).
    
    Returns:
        float: The mean distance between the points in the two clusters.
    """
    ### BEGIN SOLUTION
    return cdist(cluster1, cluster2).mean()
    ### END SOLUTION

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[13,14,15], [16,17,18], [19,20,21], [5,45,1], [1,12,7]])

epsilon = 1e-3
assert abs(d_mean(x, y) - 22.297) < epsilon, "Result is not correct: {}".format(d_mean(x, y))
assert d_mean(x, y) == d_mean(y, x), "X,Y is not equal to Y,X: {} != {}".format(d_mean(x, y), d_mean(y, x))

In [ ]:
def d_centroid(cluster1, cluster2):
    """
    Calculate the distance between the centroids of two clusters.
    
    Args:
        cluster1 (ndarray): Points belonging to cluster 1 of shape (num_points, num_dimensions).
        cluster2 (ndarray): Points belonging to cluster 1 of shape (num_points, num_dimensions).
    
    Returns:
        float: The distance between the centroids of two clusters.
    """
    ### BEGIN SOLUTION
    centroid1 = cluster1.mean(axis=0)
    centroid2 = cluster2.mean(axis=0)
    return np.linalg.norm(centroid1 - centroid2)
    ### END SOLUTION


x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[13,14,15], [16,17,18], [19,20,21]])
z = np.array([[-2,0], [-1,100]])
w = np.array([[2,0], [1,100], [1,-100], [1,-20]])

epsilon = 1e-3
assert abs(d_centroid(x, y) - 20.785) < epsilon, "Result is not correct: {}".format(d_centroid(x, y))
assert abs(d_centroid(z, w) - 55.069) < epsilon, "Result is not correct: {}".format(d_centroid(z, w))
assert d_centroid(x, y) == d_centroid(y, x), "X,Y is not equal to Y,X: {} != {}".format(d_centroid(x, y), d_centroid(y, x)) 

 # Assignment 3: Hierarchical Clustering (5 points)
 
 Consider the following matrix of distances
 
|       |  a  |  b  |  c  |  d  |  e  |
|-------|-----|-----|-----|-----|-----|
| **a** |  0  |  2  |  6  |  10 |  9  |
| **b** |  2  |  0  |  5  |  9  |  8  |
| **c** |  6  |  5  |  0  |  4  |  5  |
| **d** |  10 |  9  |  4  |  0  |  3  |
| **e** |  9  |  8  |  5  |  3  |  0  |
 

## a) Perform agglomerative clustering

Do *agglomerative* average linkage clustering by hand (i.e. employing the *mean* cluster distance). Analyze how many alternatives you have to consider at each step.

Given a set $C$ with cardinality $|n|$ we start with $n$ singleton sets, our initiaial clusters, and then have $\tfrac12 n(n-1)$ options to join two of theses cluster to form a new one: in our example we could pair $a$ with any of the 4 other elements $b,c,d,e$, or $b$ with ony of the elements $c,d,e$, or $c$ with either $d$ or $e$, or $d$ with $e$, that is $\tfrac12\cdot5\cdot(5-1)=10$ possible pairs. 

A simple heuristic is to always merge clusters with the smallest inter-cluster distance (the most similar clusters) according to the cluster distance $d_{mean}$. In our case, in the first step this will be the clusters $\{a\}$ and $\{b\}$ with $d_{mean}(\{a\},\{b\})=2$ (as for singleton sets, the average distance is just the object distance, given in the matrix). 

To proceed further, we have to update our distance matrix to contain the new cluster:
 
|             |  $\{a,b\}$ |  $\{c\}$  |  $\{d\}$  |  $\{e\}$ |
|-------------|------------|-----------|-----------|----------|
| **{a,b}**   |  $0.0$     |  $5.5$    |  $9.5$    |  $8.5$   |
| **c**       |  $5.5$     |  $0.0$    |  $4.0$    |  $5.0$   |
| **d**       |  $9.5$     |  $4.0$    |  $0.0$    |  $3.0$   |
| **e**       |  $8.5$     |  $5.0$    |  $3.0$    |  $0.0$      |

Now use this matrix to continue the process: the smallest distance is between $\{d\}$ and $\{e\}$, so these to clusters are merged to a new cluster $\{d,e\}$ and the cluster distance matrix has to be updated accordingly:

|               |  $\{a,b\}$ |  $\{c\}$  |  $\{d,e\}$  |
|---------------|------------|-----------|-------------|
| **{a,b}**     |  $0.0$     |  $5.5$    |  $9.0$      |
| **{c}**       |  $5.5$     |  $0.0$    |  $4.5$      |
| **{d,e}**     |  $9.0$     |  $4.5$    |  $0.0$      |

Now the smallest distance is between clusters $\{c\}$ and $\{d,e\}$, and joining these cluster and updating the distance matrix yields:

|             |  $\{a,b\}$   |  $\{c,d,e\}$  |
|-------------|--------------|---------------|
| **{a,b}**   |  $0.0$       |  $7.83$       |
| **{c,d,e}** |  $7.83$      |  $0.0$        |

So in total wie get the following dendrogram


                        {a,b,c,d,e}
                            | 7.83
               +------------+-------------+
               |                          |
               |                       {c,d,e}
               |                          | 4.5
               |                 +--------+---------+
               |                 |                  |
               |                 |                {d,e}
               |                 |                  | 3.0
             {a,b}               |             +----+----+
               | 2.0             |             |         |
        +------+------+          |             |         |
        |             |          |             |         |
       {a}           {b}        {c}           {d}       {e}

## b) Perform divisive clustering

Now try to do divisive average linkage clustering. Again, analyze how many splits are possible in the first step? Think of a strategy that allows to reduce this number and use this in your computation. Then apply the strategy to obtain a hierarchical clustering, that is iteratively split clusters until all clusters are singletons.

Having a set $C$ of cardinality $|C|=n$, there are in total $2^{n-1}-1$ possibilities to split it into two non-empty sets $A$ and $B$: each element of $C$ can either be assigned to $A$ or to $B$ giving $2^n$ possible ways of assigning elements of $C$ to $A$ and $B$. This number includes symmetric cases (e.g. "AABAB" is equivalent to "BBABA") and the empty set (that is "AAAAA"), so removing these leads to $\frac{2^n}{2}-1$. That is, in our case we would have to analyze $2^{5-1}-1=15$ splits.

This number grows exponentially large with the cardinality of $C$, making considering all possible splits not an options even for medium-sized sets $C$. Hence one has to apply some heuristics to find a good solution. There are of course several valid ideas here.

One such heuristic, based on ideas from Macnaughton-Smith et al (1964) is called DIANA (from DIvisive
ANAlysis) and it works as follows: First single out the single element to form a cluster of its own, such that the cluster distance to the other elements is maximized. Then elementwise grow this cluster. This will give the first split into two clusters $A$ and $B$. Then recursively apply this procedure to the resulting clusters.

In our example, this strategy works as follows: First we find one element $\{a,b,c,d,e\}$ such that the cluster distance (according to the $d_{mean}$ metric) to the remaining elements is maximized:
 
|  $S_1$  |  $C_1$        |  $d_{mean}(S_1,C_1)$                   |
|---------|---------------|----------------------------------------|
| $\{a\}$ | $\{b,c,d,e\}$ |  $(2  + 6 + 10 + 9)/4 = \mathbf{6.75}$ |
| $\{b\}$ | $\{a,c,d,e\}$ |  $(2  + 5 +  9 + 8)/4 = 6.00$          |
| $\{c\}$ | $\{a,b,d,e\}$ |  $(6  + 5 +  4 + 5)/4 = 5.00$          |
| $\{d\}$ | $\{a,b,c,e\}$ |  $(10 + 9 +  4 + 3)/4 = 6.50$          |
| $\{e\}$ | $\{a,b,c,e\}$ |  $(9  + 8 +  5 + 3)/4 = 6.24$          |

So the singleton $S_1=\{a\}$ has the largest distance to the other elements. Now repeat this, finding the next single element from $C_1$ that maximizes the distance to the remaining elements:

|  $S_2$  |  $C_2$      | $d_{mean}(S_2,C_2)$      | $d_{mean}(S_2,S_1)$ | $d_{mean}(S_2,C_2)-d_{mean}(S_2,S_1)$ | 
|---------|-------------|--------------------------|---------------------|-----------------------------|
| $\{b\}$ | $\{c,d,e\}$ | $(5+9+8)/3 \approx 7.33$ | $2.00$              | $\mathbf{5.33}$             |
| $\{c\}$ | $\{b,d,e\}$ | $(5+4+5)/3 \approx 4.67$ | $6.00$              | $-1.33$                     |
| $\{d\}$ | $\{b,c,e\}$ | $(9+4+3)/3 \approx 5.33$ | $10.00$             | $-4.67$                     |
| $\{e\}$ | $\{b,c,e\}$ | $(8+5+3)/3 \approx 5.33$ | $9.00$              | $-3.67$                     |

So element $b$ should be clustered together with element $a$. Now repeat this procedure for the remaining three element $\{c,d,e\}$:

|  $S_3$  |  $C_3$    | $d_{mean}(S_3,C_3)$ | $d_{mean}(S_3,S_2)$ | $d_{mean}(S_3,C_3)-d_{mean}(S_2,S_2)$ | 
|---------|-----------|---------------------|---------------------|---------------------------------------|
| $\{c\}$ | $\{d,e\}$ | $(4+5)/2 = 4.50$    | $(6+5)/2=5.50$      | $-1.00$                               |
| $\{d\}$ | $\{c,e\}$ | $(4+3)/2 = 3.50$    | $(10+9)/2=9.50$     | $-6.00$                               |
| $\{e\}$ | $\{c,e\}$ | $(5+3)/2 = 4.00$    | $(9+8)/2=8.50$      | $-4.5$                                |

Now all differences are negative, meaning that moving a further element from $\{c,d,e\}$ to $\{a,b\}$ will not give an improvement. Hence in the first split we split the set $C=\{a,b,c,d,e\}$ into the two clusters
$A=\{a,b\}$ and $B=\{c,d,e\}$. Now recursively apply this procedure to $A$ and $B$, starting with the cluster with the largest diameter (highest maximal distance between its objects). The diameter of $A$ is $2$ and for $B$ it is $5$. Applying the procedure to $B$ will result in the clusters $\{c\}$ and $\{d,e\}$, the diameter of $\{d,e\}$ being $3$. Hence one first splits the set into $\{d\}$ and $\{e\}$ and then $A$ into $\{a\}$ and $\{b\}$.

```

              {a,b,c,d,e}
                   |
        +----------+------------+
        |                       |
        |                    {c,d,e} D=5
        |                       |
        |                +------+------+
        |                |             |
        |                |           {d,e} D=3
        |                |             |
      {a,b} D=2          |        +----+----+
        |                |        |         |
    +-------+            |        |         |
    |       |            |        |         |
   {a}     {b}          {c}      {d}       {e}
```

* Macnaughton-Smith, P., Williams, W. T., Dale, M. B. , and Mockett, L. G. (1964), *Dissimilarity analysis: A new technique of hierarchical sub-division*, Nature, 202, 1034-1035.

## c) Linkage criteria

In the following you find implementations for single- and complete-linkage clustering. Take a look at the code  and answer the question posted below. You may of course change parameters and try it out on different datasets (`points.txt` & `clusterData.txt` are provided).

Note that for performance reasons the code differs from the lecture's pseudocode (ML-05 Slide 8), but in general it does the same.

In [ ]:
from scipy.spatial.distance import cdist

def linkage(data, k=5, complete=False):
    """
    Runs single or complete linkage clustering.
    
    Args:
        data (ndarray): Data points to be clustered in an array with shape (num_points, 2).
        k (int): Number of clusters.
        complete (bool): Whether to run complete linkage clustering.
        
    Returns:
        ndarray: The cluster labels for each data point. Shape is (num_points).
    """
    # Initially all points are their own cluster.
    labels = np.arange(len(data))

    # Calculate distance between all points.
    # Also removing half of the matrix because 
    # its symmetrical along the diagonal.
    dst = np.tril(cdist(data, data))

    while len(set(labels)) > k:
        # Get the lowest distance of two points which
        # do not have the same label.
        r, c = np.where(dst == np.min(dst[dst > 0]))
        
        # Ignore the case when there are multiple with
        # equally smallest distance.
        r = r[0]
        c = c[0]

        # The two points are now in the same cluster,
        # so they have a distance of 0 now.
        dst[r, c] = 0

        # Make the two clusters have the same label.
        labels[labels == labels[r]] = labels[c]

        # Check if we want to do complete linkage clustering.
        if complete:
            # Update the distances of the points which are not in the same cluster.
            for i in np.nonzero(dst[r, :] > 0)[0]:
                dst[r, i] = np.max(cdist(data[i, None], data[labels == labels[r], :]))

            # The distances to c are now the same as to r, so we can just
            # set them to zero - would be duplicates otherwise.
            dst[:, c] = 0

    return labels

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# Read the data.
data = np.loadtxt('points.txt')

# Show unprocessed data set.
fig_cluster = plt.figure()
plt.scatter(data[:, 0], data[:, 1])
plt.title('Unprocessed Cluster Data')
fig_cluster.canvas.draw()

# Apply Single Linkage Clustering
labels = linkage(data, k=5, complete=False)
unique, inverse, counts = np.unique(labels, return_inverse=True, return_counts=True)
print("Single Linkage Clustering:")
# Print the unqiue labels and their occurence
for u, c in zip(unique, counts):
    print("Label: {:4},  Occurence: {:4}".format(u, c))    
# Replace labels by continuous values starting from 1 for discernible colors in plot
labels = np.arange(1,unique.size+1)[inverse]
fig_single = plt.figure()
plt.scatter(data[:, 0], data[:, 1], c=labels)
plt.title('Single-linkage Clustering with k=5')
fig_single.canvas.draw()


# Apply Complete Linkage Clustering
labels = linkage(data, k=5, complete=True)
unique, inverse, counts = np.unique(labels, return_inverse=True, return_counts=True)
print("Complete Linkage Clustering:")
for u, c in zip(unique, counts):
    print("Label: {:4},  Occurence: {:4}".format(u, c))    
labels = np.arange(1,unique.size+1)[inverse]
fig_complete = plt.figure()
plt.scatter(data[:, 0], data[:, 1], c=labels)
plt.title('Complete-linkage Clustering with k=5')
fig_complete.canvas.draw()

# Test different parameters above
### BEGIN SOLUTION
### END SOLUTION

What is the difference between single- and complete-linkage clustering and which is the better solution given the dataset?

Single-linkage tends to chain clusters along the data. That is why it combines the points in the center area with those in the bottom right corner.

Complete-linkage prefers compact clusters and thus combines each of the point heavy areas individually without merging them.

For this dataset, complete-linkage is superior.